---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-stg
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-stg
  chart:
    git: git@github.com:sam-calvert/helm-operator-get-started.git
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: public.ecr.aws/y5n2l7b6/fluxcd_capacitor
      tag: stg-hdtwcel9
    replicaCount: 1
    hpa:
      enabled: false
